"""empty message

Revision ID: 923fbe81735e
Revises: 
Create Date: 2025-12-25 22:20:46.505515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923fbe81735e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), server_default="':character varying", nullable=False))
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
